feat : add absent list and today date on standup page
HugoPerard/standup-app pull request #30
Opened 2021-09-16 14:04 UTC by taoufik35

2021-09-16 14:59 UTC, yoannfleurydev requested changes
Y a quelques soucis de nommage entre

- speaker
- user
- people/person

il faudrait trouver un seul nom et rester avec tout le long sauf si la situation nécessite plus de contexte.

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +  getSpeakerabsent,
`getAbsentSpeaker` serait plus correct

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +  const [isAbsentePeople, setIsAbsentePeople] = useState([]);
Attention au nommage: `absentPeople` car c'est un tableau, pas un booléen.

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +    console.log('before');
Attention au `console.log`, à retirer avant le merge.

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +    console.log('after', usersId);
`console.log` à retirer

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +                  left="250px"
Les `px` sont à éviter, y a-t-il une raison valable de les avoir ici ?

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +                        width="250px"
Même remarque sur les `px` ici.

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +                              onSubmit={(value) => handleAddProject(value)}
```suggestion
                              onSubmit={handleAddProject}
```

Ici tu peux passer juste la fonction

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/standup.firebase.ts
> +  //   });
Pas mal de code commenté, à supprimer ?

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/standup.firebase.ts
> +  console.log(docs);
Attention au `console.log` ici

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/standup.firebase.ts
> +import { on } from 'process';
Je pense que les imports ici ne sont pas voulu.

2021-09-16 14:59 UTC, yoannfleurydev commented on src/app/standup/standup.firebase.ts
> +export const getSpeakerabsent = async (speakerId = null): Promise<any> => {
Il faudrait typer la `Promise`

2021-09-16 15:01 UTC, yoannfleurydev commented on src/app/standup/_partials/StandupNav.tsx
> +          color="yellow.500"
Si je dis pas de bêtise, je crois que le jaune est plutôt celui de `brand` que de `yellow`

2021-09-16 16:35 UTC, taoufik35 commented on src/app/standup/PageStandup.tsx
> +  getSpeakerabsent,
cette fonction n'existe plus ont a récuperé le hook d'hugo `useSpeakers`

2021-09-16 17:56 UTC, taoufik35 commented on src/app/standup/_partials/StandupNav.tsx
> +          color="yellow.500"
aucune référence couleur pour `brand` il s'agit bien de la couleur `yellow.500`

2021-09-16 17:58 UTC, taoufik35 commented on src/app/standup/PageStandup.tsx
> +                              onSubmit={(value) => handleAddProject(value)}
cette parti du code a été réaliser par Hugo mais je peux corriger s'il le faut

2021-09-16 21:46 UTC, yoannfleurydev commented on src/app/standup/_partials/StandupNav.tsx
> +          color="yellow.500"
Si si, y a bien `brand`, c'est juste l'éditeur de code qui complète pas 😉 

https://github.com/HugoPerard/standup-app/blob/bd1f29994ab1e5f0237e80384b9bb5155892f887/src/theme/foundations/colors.ts#L6-L17

2021-09-16 21:47 UTC, yoannfleurydev commented on src/app/standup/PageStandup.tsx
> +                              onSubmit={(value) => handleAddProject(value)}
Comme tu le sens, les deux se font.

2021-09-17 08:14 UTC, taoufik35 commented on src/app/standup/_partials/StandupNav.tsx
> +          color="yellow.500"
le brand est une couleur qui tire vers le bleu tout les autres élément crée en jaune (par Hugo) son en yellow.500 ex : titre bearstudio, bouton meet

2021-09-17 08:24 UTC, yoannfleurydev commented on src/app/standup/_partials/StandupNav.tsx
> +          color="yellow.500"
Ah, pas ouf ça. Ça marche 👌🏻

2021-09-27 20:06 UTC, merged